# Generated by Django 4.1.5 on 2023-01-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioningType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hp', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('cylinders', models.IntegerField()),
                ('prod', models.CharField(max_length=255)),
                ('valves', models.IntegerField()),
                ('engine_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('engine2_type_id', models.IntegerField()),
                ('generation', models.CharField(max_length=255)),
                ('doors_number', models.IntegerField()),
                ('gearbox_id', models.IntegerField()),
                ('fuel_tank_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_type_id', models.IntegerField()),
                ('avg_fuel_consumption', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prod_year_start', models.DateField()),
                ('engine1_type_id', models.IntegerField()),
                ('body_type_id', models.IntegerField()),
                ('prod_year_end', models.DateField()),
                ('engines', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('seats_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=255)),
                ('generation_id', models.IntegerField()),
                ('brand_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoofType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Upholstery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('offers_count', models.IntegerField()),
                ('f_name', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField()),
                ('nick', models.CharField(max_length=255)),
                ('mail_url_id', models.IntegerField()),
                ('account_creation_date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('views_count', models.IntegerField()),
                ('gps', models.BooleanField()),
                ('registration_number', models.CharField(max_length=255)),
                ('vin_number', models.CharField(max_length=255)),
                ('price_netto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production_year', models.IntegerField()),
                ('make', models.CharField(max_length=255)),
                ('is_after_accident', models.BooleanField()),
                ('mileage', models.IntegerField()),
                ('abs', models.BooleanField()),
                ('offer_creation_date', models.DateField()),
                ('cruise_control', models.BooleanField()),
                ('usb_port', models.BooleanField()),
                ('electric_seats', models.BooleanField()),
                ('is_damaged', models.BooleanField()),
                ('is_garaged', models.BooleanField()),
                ('bluetooth', models.BooleanField()),
                ('air_conditioning_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.airconditioningtype')),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.enginetype')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.fueltype')),
                ('images', models.ManyToManyField(to='MainPage.image')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.model')),
                ('roof_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.rooftype')),
                ('upholstery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.upholstery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.user')),
            ],
        ),
    ]
