# Generated by Django 4.1.5 on 2023-01-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_remove_offer_air_conditioning_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirConditioningType',
        ),
        migrations.DeleteModel(
            name='BodyType',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='EngineType',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
        migrations.DeleteModel(
            name='Gearbox',
        ),
        migrations.DeleteModel(
            name='Generation',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='RoofType',
        ),
        migrations.DeleteModel(
            name='Upholstery',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
